# Global
seed: 42
exp_name: linear_probing
description: linear probing on hidden states to predict judge reward
device: cuda
save_dir: /root/hidden_prob/exp1_math/outputs/

# Dataset
dataset:
  hiddens_path_train: /root/autodl-tmp/exp1_math/hs/Qwen2.5-3B-Instruct/hs_math_train_en_n32_tokens1024.pt
  hiddens_path_test: /root/autodl-tmp/exp1_math/hs/Qwen2.5-3B-Instruct/hs_math_test_en_n32_tokens1024.pt
  reward_path_train: /root/autodl-tmp/exp1_math/judge/reward_math_train_en_n32_tokens1024.pt
  reward_path_test: /root/autodl-tmp/exp1_math/judge/reward_math_test_en_n32_tokens1024.pt
  layer_idx: 21
  split_ratio: 0.9

# Model
model:
  input_dim: 2048
  output_dim: 1

# Training
train:
  batch_size: 32
  num_epochs: 30

# Optimizer
optimizer:
  optimizer_type: 'AdamW'
  AdamW: 
    lr: 1.0e-3
    weight_decay: 0.0
  SGD:
    lr: 1.0e-3
    weight_decay: 0.0
  
# Scheduler (CosineAnnealingLR)
scheduler:
  T_max: 20
  eta_min: 0.0
